# fly.toml app configuration file generated for shubh-plan-demo on 2026-08-27T09:57:52+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shubh-plan-demo'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_MODE = 'demo'
  PORT = '8080'
  SHUBH_DATA_DIR = '/app/data'

[[mounts]]
  source = 'shubh_plan_web_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '15s'
    initial_delay = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
